# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegisterAccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(845, 487)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-70, -30, 971, 551))
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(270, 50, 311, 411))
        self.frame.setStyleSheet("background-color: rgba(0, 0, 0, 127); \n"
"border: rgba(0, 0, 0, 127);\n"
"border-radius: 20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(70, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Khmer UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(0, 0, 0, 0); \n"
"border: rgba(0, 0, 0, 0);\n"
"font: 75 16pt \"Noto Sans Khmer UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 60, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Khmer UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 0, 0); \n"
"border: rgba(0, 0, 0, 0);\n"
"font: 75 12pt \"Noto Sans Khmer UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(50, 130, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Khmer UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgba(0, 0, 0, 0); \n"
"border: rgba(0, 0, 0, 0);\n"
"font: 75 12pt \"Noto Sans Khmer UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(50, 160, 201, 31))
        self.password.setStyleSheet("font: 75 12pt \"Noto Sans Khmer UI\";\n"
"color: rgb(255, 255, 255);")
        self.password.setObjectName("password")
        self.username = QtWidgets.QLineEdit(self.frame)
        self.username.setGeometry(QtCore.QRect(50, 90, 201, 31))
        self.username.setStyleSheet("font: 75 12pt \"Noto Sans Khmer UI\";\n"
"color: rgb(255, 255, 255);")
        self.username.setObjectName("username")
        self.button_register = QtWidgets.QPushButton(self.frame)
        self.button_register.setGeometry(QtCore.QRect(80, 350, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.button_register.setFont(font)
        self.button_register.setStyleSheet("background-color: rgb(224, 27, 36);\n"
"color: rgb(255, 255, 255);")
        self.button_register.setObjectName("button_register")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(50, 200, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Khmer UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgba(0, 0, 0, 0); \n"
"border: rgba(0, 0, 0, 0);\n"
"font: 75 12pt \"Noto Sans Khmer UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.repeat_password = QtWidgets.QLineEdit(self.frame)
        self.repeat_password.setGeometry(QtCore.QRect(50, 230, 201, 31))
        self.repeat_password.setStyleSheet("font: 75 12pt \"Noto Sans Khmer UI\";\n"
"color: rgb(255, 255, 255);")
        self.repeat_password.setText("")
        self.repeat_password.setObjectName("repeat_password")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(50, 270, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Khmer UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgba(0, 0, 0, 0); \n"
"border: rgba(0, 0, 0, 0);\n"
"font: 75 12pt \"Noto Sans Khmer UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.name = QtWidgets.QLineEdit(self.frame)
        self.name.setGeometry(QtCore.QRect(50, 300, 201, 31))
        self.name.setStyleSheet("font: 75 12pt \"Noto Sans Khmer UI\";\n"
"color: rgb(255, 255, 255);")
        self.name.setText("")
        self.name.setObjectName("name")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(-3, -3, 861, 501))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("pebble.jpeg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        self.label.raise_()
        self.frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Register Account"))
        self.label_3.setText(_translate("MainWindow", "Username"))
        self.label_4.setText(_translate("MainWindow", "Password"))
        self.password.setPlaceholderText(_translate("MainWindow", "password"))
        self.username.setPlaceholderText(_translate("MainWindow", "username"))
        self.button_register.setText(_translate("MainWindow", "Register"))
        self.label_7.setText(_translate("MainWindow", "Repeat Password"))
        self.repeat_password.setPlaceholderText(_translate("MainWindow", "repeat password"))
        self.label_6.setText(_translate("MainWindow", "Name"))
        self.name.setPlaceholderText(_translate("MainWindow", "name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
